$schema: "http://json-schema.org/draft-07/schema#"
title: "bids2nf Configuration Schema"
description: "JSON Schema for validating bids2nf configuration files"
type: object

# Define reusable schema components
definitions:
  entity_value:
    type: string
    pattern: "^[a-zA-Z0-9-]+$"
    description: "Valid BIDS entity value (alphanumeric and hyphens only)"
  
  file_extension:
    type: string
    enum: ["nii", "nii.gz", "json", "tsv", "bval", "bvec", "txt"]
    description: "Supported file extensions"
  
  additional_extensions:
    type: array
    items:
      $ref: "#/definitions/file_extension"
    uniqueItems: true
    description: "Additional file extensions beyond the default nii.gz and json"
  
  grouping_config:
    type: object
    properties:
      description:
        type: string
        description: "Human-readable description of this grouping"
      flip:
        type: string
        pattern: "^flip-[0-9]+$"
        description: "Flip angle specification"
      mtransfer:
        type: string
        enum: ["mt-on", "mt-off"]
        description: "Magnetization transfer status"
      echo:
        type: string
        pattern: "^echo-[0-9]+$"
        description: "Echo specification"
      run:
        type: string
        pattern: "^run-[0-9]+$"
        description: "Run specification"
      task:
        $ref: "#/definitions/entity_value"
        description: "Task specification"
      session:
        $ref: "#/definitions/entity_value"
        description: "Session specification"
      acquisition:
        $ref: "#/definitions/entity_value"
        description: "Acquisition specification"
    required: ["description"]
    additionalProperties: true
    description: "Configuration for a specific entity-based grouping"

# Main schema properties
properties:
  # MTS (Magnetization Transfer Saturation) configuration
  MTS:
    type: object
    properties:
      named_set:
        type: object
        properties:
          T1w:
            $ref: "#/definitions/grouping_config"
            properties:
              flip:
                type: string
                pattern: "^flip-[0-9]+$"
              mtransfer:
                type: string
                enum: ["mt-off"]
            required: ["description", "flip", "mtransfer"]
          
          MTw:
            $ref: "#/definitions/grouping_config"
            properties:
              flip:
                type: string
                pattern: "^flip-[0-9]+$"
              mtransfer:
                type: string
                enum: ["mt-on"]
            required: ["description", "flip", "mtransfer"]
          
          PDw:
            $ref: "#/definitions/grouping_config"
            properties:
              flip:
                type: string
                pattern: "^flip-[0-9]+$"
              mtransfer:
                type: string
                enum: ["mt-off"]
            required: ["description", "flip", "mtransfer"]
        
        required: ["T1w", "MTw", "PDw"]
        additionalProperties:
          $ref: "#/definitions/grouping_config"
        description: "Entity-based grouping configurations for MTS"
      
      required:
        type: array
        items:
          type: string
          enum: ["T1w", "MTw", "PDw"]
        uniqueItems: true
        minItems: 1
        description: "List of required groupings that must be present"
      
      additional_extensions:
        $ref: "#/definitions/additional_extensions"
        description: "Additional file extensions for MTS data"
    
    required: ["named_set", "required"]
    additionalProperties: false
    description: "MTS (Magnetization Transfer Saturation) configuration"
  
  # BOLD fMRI configuration (example for extensibility)
  BOLD:
    type: object
    properties:
      named_set:
        type: object
        patternProperties:
          "^[A-Za-z0-9]+$":
            $ref: "#/definitions/grouping_config"
        additionalProperties: false
        description: "Entity-based grouping configurations for BOLD"
      
      required:
        type: array
        items:
          type: string
        uniqueItems: true
        minItems: 1
        description: "List of required groupings for BOLD"
    
    required: ["named_set", "required"]
    additionalProperties: false
    description: "BOLD fMRI configuration"
  
  # DWI configuration (example for extensibility)
  DWI:
    type: object
    properties:
      named_set:
        type: object
        patternProperties:
          "^[A-Za-z0-9]+$":
            $ref: "#/definitions/grouping_config"
        additionalProperties: false
        description: "Entity-based grouping configurations for DWI"
      
      required:
        type: array
        items:
          type: string
        uniqueItems: true
        minItems: 1
        description: "List of required groupings for DWI"
    
    required: ["named_set", "required"]
    additionalProperties: false
    description: "Diffusion Weighted Imaging configuration"
  
  # Sequential set configuration (for VFA, MEGRE, etc.)
  VFA:
    type: object
    properties:
      sequential_set:
        type: object
        properties:
          by_entity:
            type: string
            enum: ["flip", "echo", "inversion", "run", "task", "session", "acquisition"]
            description: "Single entity to group sequentially"
          by_entities:
            type: array
            items:
              type: string
              enum: ["flip", "echo", "inversion", "run", "task", "session", "acquisition"]
            uniqueItems: true
            minItems: 2
            description: "Multiple entities to group sequentially"
          order:
            type: string
            enum: ["hierarchical", "flat"]
            default: "flat"
            description: "Ordering strategy for multiple entities"
        oneOf:
          - required: ["by_entity"]
          - required: ["by_entities"]
        additionalProperties: false
        description: "Sequential grouping configuration"
      
      additional_extensions:
        $ref: "#/definitions/additional_extensions"
        description: "Additional file extensions for VFA data"
    
    required: ["sequential_set"]
    additionalProperties: false
    description: "Sequential set configuration"
  
  # Mixed set configuration (for MPM and other complex cases)
  MPM:
    type: object
    properties:
      mixed_set:
        type: object
        properties:
          named_dimension:
            type: string
            enum: ["acq", "acquisition", "flip", "echo", "inversion", "run", "task", "session"]
            description: "Entity to use for named grouping (primary dimension)"
          sequential_dimension:
            type: string
            enum: ["flip", "echo", "inversion", "run", "task", "session", "acquisition"]
            description: "Entity to use for sequential grouping within each named group"
          named_groups:
            type: object
            patternProperties:
              "^[A-Za-z0-9]+$":
                allOf:
                  - $ref: "#/definitions/grouping_config"
                  - type: object
                    properties:
                      acq:
                        $ref: "#/definitions/entity_value"
                      acquisition:
                        $ref: "#/definitions/entity_value"
                      flip:
                        type: string
                        pattern: "^flip-[0-9]+$"
                      mt:
                        type: string
                        enum: ["mt-on", "mt-off"]
                      mtransfer:
                        type: string
                        enum: ["mt-on", "mt-off"]
            additionalProperties: false
            description: "Named group definitions with their entity constraints"
          required:
            type: array
            items:
              type: string
            uniqueItems: true
            minItems: 1
            description: "List of required named groups"
        
        required: ["named_dimension", "sequential_dimension", "named_groups"]
        additionalProperties: false
        description: "Mixed set configuration combining named and sequential grouping"
      
      additional_extensions:
        $ref: "#/definitions/additional_extensions"
        description: "Additional file extensions for MPM data"
    
    required: ["mixed_set"]
    additionalProperties: false
    description: "Mixed set configuration for complex multi-parameter data"
  
  # Plain set configuration (for DWI and other simple multi-extension cases)
  DWI:
    type: object
    properties:
      plain_set:
        type: object
        properties:
          description:
            type: string
            description: "Human-readable description of this plain set"
          required_extensions:
            type: array
            items:
              $ref: "#/definitions/file_extension"
            uniqueItems: true
            default: ["json"]
            description: "Required file extensions (nii/nii.gz is always required)"
          additional_extensions:
            $ref: "#/definitions/additional_extensions"
            description: "Additional optional file extensions"
        required: ["description"]
        additionalProperties: false
        description: "Plain set configuration for simple multi-extension data"
      
      additional_extensions:
        $ref: "#/definitions/additional_extensions"
        description: "Additional file extensions for this plain set"
    
    required: ["plain_set"]
    additionalProperties: false
    description: "Plain set configuration for DWI and similar data types"

# At least one modality must be specified
anyOf:
  - required: ["MTS"]
  - required: ["BOLD"]
  - required: ["VFA"]
  - required: ["MPM"]
  - required: ["DWI"]

additionalProperties: false

# Examples for documentation
examples:
  - MTS:
      named_set:
        T1w:
          description: "T1-weighted image assuming flip-02 is the larger flip angle"
          flip: "flip-02"
          mtransfer: "mt-off"
        MTw:
          description: "Magnetization transfer weighted image of the PD pair"
          flip: "flip-01"
          mtransfer: "mt-on"
        PDw:
          description: "Proton density weighted image assuming flip-01 is the larger flip angle"
          flip: "flip-01"
          mtransfer: "mt-off"
      required: ["T1w", "MTw", "PDw"]