name: Test bids2nf

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [17]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    
    - name: Install Nextflow
      run: |
        curl -fsSL https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
        nextflow -version
    
    - name: Run test workflows
      run: |
        nextflow run test/test_ebg_mts.nf --bids_dir $PWD/test/data/custom/ds-mtsat -profile test
        ls -la work/
    
    - name: Assert outputs
      run: |
        tree test/new_outputs
        echo "---------------------------------"
        tree test/expected_outputs
        ./test/assert_outputs.sh test/expected_outputs test/new_outputs

    - name: Validate YAML configuration
      run: |
        # Check that YAML files are valid
        python3 -c "import yaml; yaml.safe_load(open('bids2nf.yaml'))"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.java-version }}
        path: |
          work/
          .nextflow.log
          .nextflow.log.*
        retention-days: 7