name: Test bids2nf

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    
    - name: Install Nextflow
      run: |
        curl -fsSL https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
        nextflow -version
    
    - name: Pull BIDS validator container
      run: |
        docker pull agahkarakuzu/bids-validator-amd64
    
    - name: Run test workflows
      run: |
        nextflow run tests/integration/test_ebg_mts.nf --bids_dir $PWD/tests/data/custom/ds-mtsat -profile amd64
        ls -la work/
    
    - name: Assert outputs
      run: |
        echo "#️⃣ Comparing directory trees to see whether the number of files are the same ..."
        ./tests/compare_json_dirs.sh $PWD/tests/expected_outputs $PWD/tests/new_outputs
        echo "🔍 Comparing JSON files to see whether the (new/expected) content is the same ..."
        nextflow run tests/integration/assert_json_outputs.nf --expected_dir $PWD/tests/expected_outputs --new_dir $PWD/tests/new_outputs -profile arm64
        echo "🎉 All assertion tests passed!"

    - name: Validate YAML configuration
      run: |
        echo "🐒 Ensuring that you did not break the YAML config ..."
        python3 -c "import yaml; yaml.safe_load(open('bids2nf.yaml'))"
    
    - name: Debug available files
      if: always()
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Looking for nextflow logs:"
        find . -name ".nextflow.log*" -type f || echo "No nextflow log files found"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-bids2nf
        path: |
          work/
          .nextflow.log*
        retention-days: 7